import { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import * as FileSystem from 'expo-file-system';
import { getSharedObdConnection } from '../src/obd/sharedConnection';
import { parseDtcResponse } from '../src/obd/parser';
import { readDtcs, recordDtc, type DtcRecord } from '../src/database/dtcManager';
import { autoTripService } from '../src/trip/autoTripService';
export default function DtcScreen(){const [codes,setCodes]=useState<DtcRecord[]>([]);const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('');const base=`${FileSystem.documentDirectory}MERIVA_SMART`;
 async function load(){setCodes(await readDtcs(base));}
 useEffect(()=>{void load()},[]);
 async function read(){const c=getSharedObdConnection();if(!c){setMsg('Conecte o ELM327 primeiro.');return}setBusy(true);setMsg('Lendo ECU...');try{const r=await autoTripService.withPollingPaused(()=>c.session.executeCommand('03'));const found=parseDtcResponse(r.response);const old=await readDtcs(base);const now=new Date().toISOString();for(const code of found){const p=old.find(x=>x.code===code);await recordDtc(base,{code,status:'CURRENT',firstSeen:p?.firstSeen||now,lastSeen:now,occurrences:(p?.occurrences||0)+1,source:'REAL_OBD',historical:false,confirmed:true})}setMsg(found.length?found.join(', '):'Nenhum DTC retornado');await load()}catch(e){setMsg(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <ScrollView contentContainerStyle={styles.c}><Text style={styles.title}>CÓDIGOS DE FALHA</Text><Text style={styles.sub}>Separação entre falhas atuais e histórico. Nada é inventado.</Text><TouchableOpacity style={styles.btn} onPress={read} disabled={busy}><Text style={styles.btnText}>{busy?'LENDO ECU...':'LER DTC AGORA'}</Text></TouchableOpacity><Text style={styles.msg}>{msg}</Text>{codes.length?codes.map(d=><View key={d.code} style={styles.card}><View><Text style={styles.code}>{d.code}</Text><Text style={styles.meta}>{d.description||'Descrição não cadastrada'} • {d.status}</Text></View><Text style={d.confirmed?styles.confirmed:styles.pending}>{d.confirmed?'CONFIRMADO':'PENDENTE'}</Text></View>):<View style={styles.empty}><Text>Nenhum código armazenado.</Text></View>}</ScrollView>}
const styles=StyleSheet.create({c:{flexGrow:1,padding:16,backgroundColor:'#f5f7fb'},title:{fontSize:23,fontWeight:'900',color:'#123c70'},sub:{color:'#64748b',marginVertical:8},btn:{backgroundColor:'#1769d1',padding:14,borderRadius:10,alignItems:'center'},btnText:{color:'#fff',fontWeight:'900'},msg:{color:'#475569',marginVertical:10},card:{backgroundColor:'#fff',padding:14,borderRadius:12,borderWidth:1,borderColor:'#dce4ee',marginBottom:8,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},code:{fontSize:20,fontWeight:'900',color:'#c7373f'},meta:{fontSize:10,color:'#64748b',marginTop:4},confirmed:{color:'#c7373f',fontSize:9,fontWeight:'900'},pending:{color:'#d97706',fontSize:9,fontWeight:'900'},empty:{padding:18,backgroundColor:'#fff',borderRadius:12}});
