import { useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import * as FileSystem from 'expo-file-system';
import { Elm327Session } from '../src/obd/elm327';
import { parseDtcResponse, parsePidResponse } from '../src/obd/parser';
import { SimulatedObdTransport } from '../src/obd/simulatedTransport';
import { BluetoothDeviceInfo } from '../src/obd/bluetoothClassicTransport';
import { createRealElmSession, discoverPairedDevices } from '../src/obd/bluetoothManager';
import { discoverSupportedPids, KNOWN_PIDS } from '../src/obd/pidScanner';
import { DtcRecord, readDtcs, recordDtc } from '../src/database/dtcManager';
import { initAutoSave, startObdSessionCheckpoint, stopObdSessionCheckpoint, updateAutoSaveState } from '../src/meriva/autosaveManager';
import { forceSaveOnObdEvent, registerObdQuery } from '../src/meriva/autosaveIntegration';

type Mode='REAL'|'SIMULACAO';
const basePath=()=>`${FileSystem.documentDirectory}MERIVA_SMART`;

export default function LaboratorioScreen(){
 const [mode,setMode]=useState<Mode>('REAL'),[devices,setDevices]=useState<BluetoothDeviceInfo[]>([]),[selectedAddress,setSelectedAddress]=useState(''),[pid,setPid]=useState('010C'),[tx,setTx]=useState(''),[rx,setRx]=useState(''),[elapsedMs,setElapsedMs]=useState<number|null>(null),[status,setStatus]=useState('PREPARANDO AUTOSAVE'),[protocol,setProtocol]=useState('N/D'),[error,setError]=useState(''),[loadingDevices,setLoadingDevices]=useState(false),[storageReady,setStorageReady]=useState(false),[supportedPids,setSupportedPids]=useState<string[]>([]),[dtcCodes,setDtcCodes]=useState<string[]>([]);
 const sessionRef=useRef<Elm327Session|null>(null), autoSaveReadyRef=useRef(false);
 const simulationSession=useMemo(()=>new Elm327Session(new SimulatedObdTransport()),[]);
 useEffect(()=>{let mounted=true;void initAutoSave(basePath()).then(state=>{autoSaveReadyRef.current=true;if(mounted){setStorageReady(true);setProtocol(state.obd.protocol??'N/D');setStatus('PRONTO PARA CONEXÃO');}}).catch(e=>{if(mounted){setStatus('FALHA NO AUTOSAVE');setError(e instanceof Error?e.message:'FALHA');}});return()=>{mounted=false;const active=sessionRef.current;sessionRef.current=null;stopObdSessionCheckpoint();if(!autoSaveReadyRef.current)return;void(async()=>{try{await active?.close();}catch{}updateAutoSaveState(s=>{s.obd={...s.obd,connected:false};});await forceSaveOnObdEvent();})();};},[]);
 async function loadDevices(){setLoadingDevices(true);setError('');try{const paired=await discoverPairedDevices();setDevices(paired);setSelectedAddress(c=>paired.some(x=>x.address===c)?c:paired[0]?.address??'');setStatus(paired.length?'ELM327 PAREADO ENCONTRADO':'NENHUM ELM327 PAREADO');}catch(e){setStatus('BLUETOOTH NÃO PRONTO');setError(e instanceof Error?e.message:'FALHA BLUETOOTH');}finally{setLoadingDevices(false);}}
 async function connectReal(){const device=devices.find(x=>x.address===selectedAddress);if(!device){setError('SELECIONE UM DISPOSITIVO');return;}setError('');setStatus('CONECTANDO ELM327...');try{if(sessionRef.current)await sessionRef.current.close();const c=await createRealElmSession(device);sessionRef.current=c.session;setProtocol(c.protocol??'N/D');startObdSessionCheckpoint();updateAutoSaveState(s=>{s.obd={connected:true,adapterName:device.name,protocol:c.protocol??undefined,lastConnectedAt:new Date().toISOString()};});setStatus(c.protocol?'ECU RESPONDENDO':'ELM RESPONDENDO / PROTOCOLO N/D');}catch(e){sessionRef.current=null;setStatus('ELM NÃO RESPONDE');setError(e instanceof Error?e.message:'FALHA AO CONECTAR');}}
 async function disconnectReal(){const active=sessionRef.current;sessionRef.current=null;setProtocol('N/D');stopObdSessionCheckpoint();try{await active?.close();updateAutoSaveState(s=>{s.obd={...s.obd,connected:false};});await forceSaveOnObdEvent();setStatus('ELM DESCONECTADO');}catch(e){setStatus('DESCONECTADO COM AVISO');setError(e instanceof Error?e.message:'FALHA AO DESCONECTAR');}}
 async function testPid(){setError('');setStatus(mode==='SIMULACAO'?'SIMULAÇÃO: CONSULTANDO':'ECU: CONSULTANDO');try{const active=mode==='SIMULACAO'?simulationSession:sessionRef.current;if(!active)throw new Error('CONECTE AO ELM327 ANTES DE TESTAR');const result=await active.queryPid(pid);await registerObdQuery(basePath(),result,mode);setTx(result.tx);setRx(result.rx);setElapsedMs(result.elapsedMs);setProtocol(result.protocol??'N/D');setStatus(mode==='SIMULACAO'?`SIMULAÇÃO: ${result.parsed.status}`:result.parsed.status==='RESPONDEU'?'ECU RESPONDENDO':'ECU NÃO RESPONDE');}catch(e){setStatus('ERRO NA CONSULTA');setError(e instanceof Error?e.message:'ERRO PID');}}
 async function discoverPids(){setError('');setStatus('DESCOBRINDO PIDs...');try{const active=mode==='SIMULACAO'?simulationSession:sessionRef.current;if(!active)throw new Error('CONECTE AO ELM327 ANTES DE DESCOBRIR');const items=await discoverSupportedPids(active);const found=Array.from(new Set(items.flatMap(x=>x.supportedPids))).sort();setSupportedPids(found);setStatus(`DESCOBERTA: ${found.length} PIDs`);}catch(e){setStatus('FALHA NA DESCOBERTA');setError(e instanceof Error?e.message:'ERRO PIDs');}}
 async function readCurrentDtcs(){setError('');setStatus('LENDO DTC...');try{const active=mode==='SIMULACAO'?simulationSession:sessionRef.current;if(!active)throw new Error('CONECTE AO ELM327 ANTES DE LER DTC');const result=await active.executeCommand('03');const codes=parseDtcResponse(result.response);setTx(result.command);setRx(result.response);setElapsedMs(result.elapsedMs);setProtocol(active.getProtocol()??'N/D');setDtcCodes(codes);if(mode==='REAL'){const existing=await readDtcs(basePath()),now=new Date().toISOString();const records:DtcRecord[]=codes.map(code=>{const previous=existing.find(x=>x.code===code);return{code,status:'CURRENT',firstSeen:previous?.firstSeen??now,lastSeen:now,occurrences:(previous?.occurrences??0)+1,source:'REAL_OBD',historical:false,confirmed:true};});for(const record of records)await recordDtc(basePath(),record);updateAutoSaveState(s=>{s.dtcs=records.length?records:existing;});await forceSaveOnObdEvent();}setStatus(codes.length?`DTC: ${codes.join(', ')}`:'NENHUM DTC RETORNADO');}catch(e){setStatus('FALHA NA LEITURA DTC');setError(e instanceof Error?e.message:'ERRO DTC');}}
 const parsed=rx?parsePidResponse(pid,rx):null,knownSupported=supportedPids.filter(x=>KNOWN_PIDS.includes(x));
 return <ScrollView contentContainerStyle={styles.container}>
  <Text style={styles.kicker}>MERIVA SMART / DIAGNÓSTICO</Text><Text style={styles.title}>LABORATÓRIO OBD</Text>
  <View style={styles.statusCard}><Text style={styles.statusLabel}>ESTADO</Text><Text style={styles.status}>{status}</Text><Text style={styles.protocol}>PROTOCOLO • {protocol}</Text></View>
  <View style={styles.tabs}><TouchableOpacity style={[styles.tab,mode==='REAL'&&styles.tabOn]} onPress={()=>setMode('REAL')}><Text style={styles.tabText}>BLUETOOTH REAL</Text></TouchableOpacity><TouchableOpacity style={[styles.tab,mode==='SIMULACAO'&&styles.simOn]} onPress={()=>setMode('SIMULACAO')}><Text style={styles.tabText}>SIMULAÇÃO</Text></TouchableOpacity></View>
  {mode==='REAL'?<><TouchableOpacity style={styles.primary} onPress={loadDevices} disabled={loadingDevices||!storageReady}>{loadingDevices?<ActivityIndicator color="#fff"/>:<Text style={styles.primaryText}>LISTAR DISPOSITIVOS PAREADOS</Text>}</TouchableOpacity>{devices.map(d=><TouchableOpacity key={d.address} style={[styles.device,selectedAddress===d.address&&styles.deviceOn]} onPress={()=>setSelectedAddress(d.address)}><Text style={styles.deviceName}>{d.name||'DISPOSITIVO SEM NOME'}</Text><Text style={styles.deviceAddr}>{d.address}</Text></TouchableOpacity>)}<TouchableOpacity style={styles.secondary} onPress={connectReal} disabled={!selectedAddress||!storageReady}><Text style={styles.secondaryText}>CONECTAR E INICIALIZAR</Text></TouchableOpacity><TouchableOpacity style={styles.secondary} onPress={()=>void disconnectReal()} disabled={!sessionRef.current}><Text style={styles.secondaryText}>DESCONECTAR</Text></TouchableOpacity></>:<Text style={styles.warning}>SIMULAÇÃO é local e não alimenta o aprendizado do veículo.</Text>}
  <View style={styles.card}><Text style={styles.cardTitle}>CONSULTA</Text><TextInput value={pid} onChangeText={setPid} autoCapitalize="characters" style={styles.input} placeholder="PID • exemplo 010C" placeholderTextColor="#64748b"/><TouchableOpacity style={styles.primary} onPress={testPid} disabled={!storageReady||(mode==='REAL'&&!sessionRef.current)}><Text style={styles.primaryText}>TESTAR PID</Text></TouchableOpacity><TouchableOpacity style={styles.secondary} onPress={discoverPids} disabled={!storageReady||(mode==='REAL'&&!sessionRef.current)}><Text style={styles.secondaryText}>DESCOBRIR PIDs SUPORTADOS</Text></TouchableOpacity><TouchableOpacity style={styles.secondary} onPress={readCurrentDtcs} disabled={!storageReady||(mode==='REAL'&&!sessionRef.current)}><Text style={styles.secondaryText}>LER DTC ATUAIS</Text></TouchableOpacity></View>
  <View style={styles.raw}><Text style={styles.rawTitle}>RESPOSTA ECU</Text><Text style={styles.rawLabel}>TX</Text><Text style={styles.rawValue}>{tx||'SEM DADOS'}</Text><Text style={styles.rawLabel}>RX</Text><Text style={styles.rawValue}>{rx||'SEM DADOS'}</Text><Text style={styles.rawLabel}>TEMPO</Text><Text style={styles.rawValue}>{elapsedMs==null?'N/D':`${elapsedMs} ms`}</Text><Text style={styles.rawLabel}>VALOR</Text><Text style={styles.rawValue}>{parsed?.value==null?'SEM DADOS':`${parsed.value} ${parsed.unit}`}</Text><Text style={styles.rawLabel}>DTC</Text><Text style={styles.rawValue}>{dtcCodes.length?dtcCodes.join(', '):'NENHUM'}</Text><Text style={styles.rawLabel}>PIDs DESCOBERTOS</Text><Text style={styles.rawValue}>{supportedPids.length} • conhecidos: {knownSupported.length}</Text></View>
  {!!error&&<View style={styles.error}><Text style={styles.errorTitle}>ATENÇÃO</Text><Text style={styles.errorText}>{error}</Text></View>}
 </ScrollView>;
}
const styles=StyleSheet.create({container:{flexGrow:1,padding:18,backgroundColor:'#0b1118'},kicker:{color:'#7dd3fc',fontSize:11,fontWeight:'800',letterSpacing:1.5},title:{color:'#f8fafc',fontSize:28,fontWeight:'900',marginBottom:16,marginTop:3},statusCard:{backgroundColor:'#111a24',borderWidth:1,borderColor:'#263646',borderRadius:15,padding:15,marginBottom:12},statusLabel:{color:'#64748b',fontSize:10,fontWeight:'900'},status:{color:'#7dd3fc',fontWeight:'900',fontSize:16,marginTop:4},protocol:{color:'#94a3b8',fontSize:11,marginTop:6},tabs:{flexDirection:'row',gap:8,marginBottom:12},tab:{flex:1,borderWidth:1,borderColor:'#334155',borderRadius:11,padding:12,alignItems:'center'},tabOn:{backgroundColor:'#123047',borderColor:'#0284c7'},simOn:{backgroundColor:'#3a2a0d',borderColor:'#d97706'},tabText:{color:'#e2e8f0',fontWeight:'800',fontSize:11},primary:{backgroundColor:'#0284c7',borderRadius:11,padding:14,alignItems:'center',marginBottom:9},primaryText:{color:'#fff',fontWeight:'900'},secondary:{backgroundColor:'#111a24',borderWidth:1,borderColor:'#334155',borderRadius:11,padding:13,alignItems:'center',marginBottom:9},secondaryText:{color:'#e2e8f0',fontWeight:'800'},device:{backgroundColor:'#111a24',borderWidth:1,borderColor:'#334155',borderRadius:11,padding:13,marginBottom:8},deviceOn:{borderColor:'#38bdf8',backgroundColor:'#102332'},deviceName:{color:'#f8fafc',fontWeight:'900'},deviceAddr:{color:'#64748b',fontSize:11,marginTop:3},warning:{color:'#fbbf24',backgroundColor:'#2a1c10',padding:12,borderRadius:10,marginBottom:12},card:{backgroundColor:'#111a24',borderWidth:1,borderColor:'#263646',borderRadius:15,padding:14,marginTop:5,marginBottom:12},cardTitle:{color:'#e2e8f0',fontWeight:'900',marginBottom:9},input:{backgroundColor:'#0b1118',borderWidth:1,borderColor:'#334155',borderRadius:10,padding:13,color:'#f8fafc',fontSize:16,marginBottom:9},raw:{backgroundColor:'#071018',borderWidth:1,borderColor:'#263646',borderRadius:15,padding:15},rawTitle:{color:'#7dd3fc',fontWeight:'900',fontSize:12,marginBottom:8},rawLabel:{color:'#64748b',fontSize:10,fontWeight:'900',marginTop:8},rawValue:{color:'#dbeafe',fontFamily:'monospace',fontSize:13,marginTop:2},error:{backgroundColor:'#32171b',borderWidth:1,borderColor:'#9f1239',borderRadius:11,padding:12,marginTop:12},errorTitle:{color:'#fb7185',fontWeight:'900'},errorText:{color:'#fecdd3',marginTop:3}
});
